name: Image
on:
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/lain-txl/flow:canary
          docker push registry.cn-hangzhou.aliyuncs.com/lain-txl/flow:canary
